### ISSUE TITLE
replace all Padding occurrences with the right padding extension.

### ISSUE THREAD

**Issue by JordyHers** [JordyHers-org/Times-up-flutter#124]
### Current Behaviour:

In the current version of the app we find at some places widgets wrapped in a padding. For instance 

```dart

Padding(
    padding: EdgeInsets.fromLTRB(20, 0, 20, 0),
     child: Container(
       padding: const EdgeInsets.all(0.0),
         color: Colors.green,
           width: 80.0,
           height: 80.0,
          ), //Container
       ),
```

### Expected Behaviour:

The app uses extensions in the theme file. with `p4` ,`vP16` etc... All the padding occurences should be replaced with this extension like in the parent page.

```dart

SizedBox(
       
         color: Colors.green,
           width: 80.0,
           height: 80.0,
          ).p4, //Container
      
```

### Steps to Reproduce:

No/

### Environment:
Emulator: 
Android version: 
Android SDK:

**Comment by JordyHers** [comment]
@Anthonycodes101 Hey there. did you take care of that issue ? Can you have. a look please

**Comment by Anthonycodes101** [comment]
I will round off soon🔜

**Comment by JordyHers** [comment]
@Anthonycodes101 Sure take your time.

**Comment by verkit** [comment]
Hello @JordyHers ,
I would like to work on this issue. Please assign me this issue

**Comment by JordyHers** [comment]
@verkit Sure. There is already a extension Padding created and accessible in the theme file inside the utils folder. You can use it to replace padding occurrences in the app. Thank you again for your contribution. 😊

**Comment by verkit** [comment]
I've already make PR, If there is any feedback. Please let me know
