### ISSUE TITLE
Fix the spacing between the texts on Splash Screen

### ISSUE THREAD

**Issue by i-am-ijaz** [JordyHers-org/Times-up-flutter#125]
There is spacing issue between the texts on the SplashScreen or OnBoarding Screen.

**Screenshots**

<img width="215" src="https://github.com/JordyHers-org/Times-up-flutter/assets/25157495/6f2876b7-1352-4181-a425-00c691536d53">
<img width="215" src="https://github.com/JordyHers-org/Times-up-flutter/assets/25157495/70ec6c43-261d-4fd4-b1cd-8648b37755d2">
<img width="215" src="https://github.com/JordyHers-org/Times-up-flutter/assets/25157495/c4c38d07-f05a-44e2-b0dc-aef1d4d31519">

**To Reproduce**

Go to Splash Screen where user can choose to login as parent or child

**Expected behavior**
There should be consistent spacing between the deep blue test heading and sub heading

**Smartphone**
 - Device: Infinix note 11
 - OS: 12
 - Version 32

**Comment by i-am-ijaz** [comment]
Spacing issue has been fixed by @JordyHers

**Comment by JordyHers** [comment]
@i-am-ijaz Great.
