### ISSUE TITLE
fix login issues for Facebook

### ISSUE THREAD

**Issue by JordyHers** [JordyHers-org/Times-up-flutter#13]
Investigate and fix the issue.

### Current Behaviour:
When trying to login using Facebook an error occurs. 
The circular progress indicator keeps loading forever

### Expected Behaviour:

Investigate and fix the issue.
 Contact @JordyHers-org/admins for Facebook credentials

### Steps to Reproduce:

- Start the app
- Accept the permissions
- Click on parent device
- Try to 

https://github.com/JordyHers-org/Times-up-flutter/assets/49708438/0b0d9dad-e045-45e0-9d5c-d25ab36cf684

sign in with Facebook

### Environment:
Emulator: Pixel 6 Pro
Android version: 12
Android SDK: 33

**Comment by bhoomikshetty** [comment]
I can fix this issue. Can you assign it to me?
