### ISSUE TITLE
fix log out issue

### ISSUE THREAD

**Issue by JordyHers** [JordyHers-org/Times-up-flutter#14]
Investigate and fix the issue.

### Current Behaviour:
Nothing occurs when the user tries to sign out. 
Dialog disappears when tap on log out

### Expected Behaviour:

Investigate and fix the issue.

### Steps to Reproduce:

- Start the app
- Log in with Google or Email
- Navigate to Settings
- Try to log out tap on the icon
- Are you sure you want to log out tap logout

<img width="212" src="https://github.com/JordyHers-org/Times-up-flutter/assets/49708438/cf951b41-e937-4d06-94cf-7acea25efa18" />

### Environment:
Emulator: Pixel 6 Pro
Android version: 12
Android SDK: 33

**Comment by bhoomikshetty** [comment]
I can work on this issue. Can you assign it to me.

**Comment by JordyHers** [comment]
@bhoomikshetty ok. I'll assign it to you.
