### ISSUE TITLE
enable `dark mode` and `light mode`

### ISSUE THREAD

**Issue by JordyHers** [JordyHers-org/Times-up-flutter#24]
### Current Behaviour:

The dark mode and light mode are not set up in the app. 

### Expected Behaviour:

The colors of the dark mode should be the opposite. 
Scaffold background color should be darker.
white text should be dark etc...

On click the entire app mode should change smoothly You can 

My approach 😁

 (just a suggestion) 

- use ChangeProviderNotifier
- create an abstract class that extends it. 
- use the methods inside like {set to dark mode}
- call `notifyListeners`
- wrap the entire App in a Consumer widget 🚀

### Steps to Reproduce:

NO/

<img width="212" src="https://github.com/JordyHers-org/Times-up-flutter/assets/49708438/f8600921-711b-49a5-94cb-f4dbd6a68e15" />

### Environment:
Emulator: Pixel 6 Pro
Android version: 12
Android SDK: 33

**Comment by siddesh3101** [comment]
can i do this with riverpod?

**Comment by JordyHers** [comment]
It's better to use just provider or changeNotifierProvider. This will avoid having different state management solutions in the project. There is already BLOC for sign-in 😁

**Comment by siddesh3101** [comment]
ok i will try to do this with provider and in case i am stuck i will update the ticket to help needed

**Comment by ckelwin** [comment]
I will be working on this.

**Comment by JordyHers** [comment]
@ckelwin Thank you man. Yes go for it. 😁

**Comment by ckelwin** [comment]
@JordyHers ready for review. Did a quick sweep to just ensure things works for now. May need a bit more touch up. Only did it for the parent app as there's no option/settings to toggle this in the child app now. Maybe a separate issue for that?

**Comment by JordyHers** [comment]
@ckelwin I will fix it up do not worry.
