### ISSUE TITLE
update readme file to say how to contribute to the project

### ISSUE THREAD

**Issue by JordyHers** [JordyHers-org/Times-up-flutter#26]
### Current Behaviour:

The current readme file is not really well structure. 
Some pictures are not aligned. There is no content table. 
Headings are not consistent.

### Expected Behaviour:

update the Readme and create a section on how to contribute to the project 

### Steps to Reproduce:

NO/

**Comment by i-am-ijaz** [comment]
This bug could not be reproduced on my environment. @JordyHers 
 
### Environment:
Emulator: Infinix note 11
Android version: 12
Android SDK: 32
