### ISSUE TITLE
change `Control` word to `Dashboard`

### ISSUE THREAD

**Issue by JordyHers** [JordyHers-org/Times-up-flutter#50]
### Current Behaviour:

The word control is written

### Expected Behaviour:

change to Dashboard

### Steps to Reproduce:

NO/

<img width="212" src="https://github.com/JordyHers-org/Times-up-flutter/assets/49708438/5a389b10-6e39-46bf-b6ce-23757c1d2019" />

### Environment:
Emulator: Pixel 6 Pro
Android version: 12
Android SDK: 33

**Comment by gantanikhilraj** [comment]
hey @JordyHers , I would like to work on this ?

**Comment by JordyHers** [comment]
@gantanikhilraj don't forget to put the issue "in Progress" if you started working on it.
