### ISSUE TITLE
Save button on add child page has black border lines

### ISSUE THREAD

**Issue by JordyHers** [JordyHers-org/Times-up-flutter#53]
### Current Behaviour:

The current screenshot shows that the button type is not the correct one.

### Expected Behaviour:

remove the border on the button or set the `color` to be transparent.

### Steps to Reproduce:

NO/

<img width="212" src="https://github.com/JordyHers-org/Times-up-flutter/assets/49708438/843740af-c5c6-4957-953b-be33f5181be5" />

### Environment:
Emulator: Pixel 6 Pro
Android version: 12
Android SDK: 33

**Comment by gantanikhilraj** [comment]
Hey @JordyHers , I would like to work on this.
