### ISSUE TITLE
Dialog is not dismissed when Notification is sent to a child. The `ok` button is not responding

### ISSUE THREAD

**Issue by JordyHers** [JordyHers-org/Times-up-flutter#54]
### Current Behaviour:

The current button does not disappear.

### Expected Behaviour:

implement a logic to retrieve the appsUsage, convert the strings into integer and sum them up to have real data.

### Steps to Reproduce:

NO/

<img width="212" src="https://github.com/JordyHers-org/Times-up-flutter/assets/49708438/bac21472-1457-409e-a71a-1a5d844c271b" />

### Environment:
Emulator: Samsung Galaxy Ultra 23
Android version: 13
Android SDK: 33

**Comment by darshsingh116** [comment]
I want to work on this issue.

**Comment by darshsingh116** [comment]
I forked your project but it is failing to build and is giving this error
![image](https://github.com/JordyHers-org/Times-up-flutter/assets/116330695/1128ec86-f1eb-4f52-9b82-00887815d87d)
how to fix this error?

**Comment by JordyHers** [comment]
@darshsingh116 it's because you do not have the API Key in your local properties. You should join the discord channel to have access to this key..
