### ISSUE TITLE
text on splash_screen is too small

### ISSUE THREAD

**Issue by JordyHers** [JordyHers-org/Times-up-flutter#59]
### Current Behaviour:

The current text on splash screen is too small 

### Expected Behaviour:

Set the auto_size_text to have a minimum and maximum fontsize.
Make sure the fontsize is consistent and no OVERFLOW ERROR occurs 
if the user increases his device font size to XL or XXL.

### Steps to Reproduce:

NO/

### Environment:
Emulator: Pixel 6 Pro
Android version: 12
Android SDK: 33

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it.
