### ISSUE TITLE
enable`UNIQUE CODE` to be shared or copied on `longPress`

### ISSUE THREAD

**Issue by JordyHers** [JordyHers-org/Times-up-flutter#60]
### Current Behaviour:

Currently the code can't be copied or shared. So the user has to manually enter in the child's device.

### Expected Behaviour:

implement the function to trigger the native android bottom sheet 

- to share `onPress`
- to copy `onLongPress`

### Steps to Reproduce:

NO/

<img width="212" src="https://github.com/JordyHers-org/Times-up-flutter/assets/49708438/9d45f8f2-fd00-4174-916d-8f801b7e5ac3" />

### Environment:
Emulator: Pixel 6 Pro
Android version: 12
Android SDK: 33

**Comment by siddesh3101** [comment]
please assign me this i will like to work on this issue

**Comment by siddesh3101** [comment]
i have added this feature.

**Comment by siddesh3101** [comment]
please close this issue

**Comment by JordyHers** [comment]
@siddesh3101 This is in ready for testing for now. I usually close issue once it's merged and working on real devices. With all the changes. But we don't have a QA tester for now. 😁 So I will have to do the QA engineer myself.
