### ISSUE TITLE
implement loggers to the project

### ISSUE THREAD

**Issue by JordyHers** [JordyHers-org/Times-up-flutter#64]
### Current Behaviour:

The current project has random print everywhere in the app.

### Expected Behaviour:

Implement a proper logger in the project :💯 

Use the logger package from pub.dev https://pub.dev/packages/logger
* Replace the print() methods in the entire project with the corresponding log

```
 Debug
 Error 
 Verbose
```

### Steps to Reproduce:

NO/

### Environment:
Emulator: Pixel 6 Pro
Android version: 12
Android SDK: 33

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it.

**Comment by JordyHers** [comment]
@tarunsamanta2k20 Sure i will add you on it during the meeting in a few hours.

**Comment by JordyHers** [comment]
@tarunsamanta2k20  please join the discord channel before starting on the project https://discord.gg/WaF54U9x

**Comment by JordyHers** [comment]
@tarunsamanta2k20 Any update on that ticket. Still working on it ?

**Comment by tarunsamanta2k20** [comment]
@JordyHers FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not create task ':app:generateDebugLintModel'.
      > java.lang.NullPointerException (no error message)

**Comment by JordyHers** [comment]
@tarunsamanta2k20 look at the #how-to channel on discord. And implement the Google Api key in the correct LOCAL.PROPERTIES FILE
