### ISSUE TITLE
app title is still 'PARENTAL CONTROL' in main.dart it should be 'Time's Up'

### ISSUE THREAD

**Issue by JordyHers** [JordyHers-org/Times-up-flutter#71]
### Current Behaviour:

app title is still 'PARENTAL CONTROL' in main.dart

### Expected Behaviour:

it should be 'Time's Up'

### Steps to Reproduce:

NO/

### Environment:
Emulator: Samsung Galaxy S23 Ultra
Android version: 13
Android SDK: 33

**Comment by mehroze-zaidi** [comment]
I'm working on it.
