### ISSUE TITLE
Trailing commas should be used to properly format the code 

### ISSUE THREAD

**Issue by i-am-ijaz** [JordyHers-org/Times-up-flutter#72]
### Current Behaviour:
In the whole code base of the app we are not using the trailing commas to format the code vertically

### Expected Behaviour:
We should use the trailing commas to properly format the code

_For more info:_ view this [link](https://dart-lang.github.io/linter/lints/require_trailing_commas.html)

**Comment by JordyHers** [comment]
@i-am-ijaz can you use this issue to implement more linting rules. For final and constant keywords etc... 

max length line : 80 char etc...

**Comment by i-am-ijaz** [comment]
@JordyHers Sure, I will implement additional linting rules in the same branch.
