### ISSUE TITLE
Save button on add child page is not working when child image is not selected

### ISSUE THREAD

**Issue by mehroze-zaidi** [JordyHers-org/Times-up-flutter#85]
**Describe the bug**
When taping on the save button showing this error on the console: "Null check operator used on a null value"

**To Reproduce**
Tap on the save button located at the app bar on add child page.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JordyHers** [comment]
@mehroze-zaidi  is the bug in the current dev branch ? Can you try to reproduce this or edit the bug report description. It is working on my side.

**Comment by mehroze-zaidi** [comment]
> @mehroze-zaidi is the bug in the current dev branch ? Can you try to reproduce this or edit the bug report description? It is working on my side.

Sorry, I forgot to mention: Save button on add child page is not working when the child image is not selected

**Comment by JordyHers** [comment]
@mehroze-zaidi I think 🤔 it's the correct behavior. But the user should be notified then. I can't remember exactly.

**Comment by mehroze-zaidi** [comment]
so if it's correct behavior, we need to have a check there so it shouldn't create this error "Null check operator used on a null value" on the console and also show the snack bar saying please select the child photo. What do you think about that?

**Comment by JordyHers** [comment]
@mehroze-zaidi YEESSSSS great initiative. I love that idea 💯. So please close that issue and open an new one with this exact description saying: 
1- replace error logger with verbose/debug 
2-  introduce a snackbar to notify user to upload a picture instead



in the version `v3.0.0` we will introduce an alternative to that . maybe assigh adefault avatar if no child's picture is uploaded.

**Comment by mehroze-zaidi** [comment]
sure.
