### ISSUE TITLE
widget overflow on child's page

### ISSUE THREAD

**Issue by JordyHers** [JordyHers-org/Times-up-flutter#99]
### Current Behaviour:

 <img width="312" src="https://user-images.githubusercontent.com/49708438/244780524-20b36295-e130-41ca-b7ad-41c130cca1d9.png" />

### Expected Behaviour:

Fix the overflow error 

### Steps to Reproduce:

1- Launch the app
2- Go the child's device
3- Register using the same credentials (As Parent)
4- Enter the child's name and the code

### Environment:
Emulator: Pixel 6 Pro
Android version: 12
Android SDK: 33

**Comment by Anthonycodes101** [comment]
Issue was not consistent
